version: '3'
services:
  mongodb:
    container_name: mongodb-${teamname:-defaultASW}
    image: mongo
    profiles: ["dev", "prod"]
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mynetwork

  authservice:
    container_name: authservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es6b/authservice:latest
    profiles: ["dev", "prod"]
    build: ./users/authservice
    depends_on:
      - mongodb
    ports:
      - "8002:8002"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb

  userservice:
    container_name: userservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es6b/userservice:latest
    profiles: ["dev", "prod"]
    build: ./users/userservice
    depends_on:
      - mongodb
    ports:
      - "8001:8001"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/userdb

  answerservice:
    container_name: answerservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es6b/answerservice:latest
    profiles: ["dev", "prod"]
    build: ./questions/answerservice
    depends_on:
      - mongodb
    ports:
      - "8004:8004"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/questiondb

  createservice:
    container_name: createservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es6b/createservice:latest
    profiles: ["dev", "prod"]
    build: ./questions/createservice
    depends_on:
      - mongodb
    ports:
      - "8005:8005"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/questiondb

  recordservice:
    container_name: recordservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es6b/recordservice:latest
    profiles: ["dev", "prod"]
    build: ./questions/recordservice
    depends_on:
      - mongodb
    ports:
      - "8006:8006"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/recorddb

  generatedquestservice:
    container_name: generatedquestservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es6b/generatedquestservice:latest
    profiles: ["dev", "prod"]
    build: ./questions/generatedquestservice
    depends_on:
      - mongodb
    ports:
      - "8003:8003"
    networks:
      - mynetwork
    environment:
      MONGODB_URI: mongodb://mongodb:27017/questiondb

  gatewayservice:
    container_name: gatewayservice-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es6b/gatewayservice:latest
    profiles: ["dev", "prod"]
    build: ./gatewayservice
    depends_on:
      - mongodb
      - userservice
      - authservice
      - answerservice
      - createservice
      - recordservice
      - generatedquestservice
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    environment:
      AUTH_SERVICE_URL: http://authservice:8002
      USER_SERVICE_URL: http://userservice:8001
      ANSW_SERVICE_URL: http://answerservice:8004
      QUES_SERVICE_URL: http://createservice:8005
      REC_SERVICE_URL: http://recordservice:8006
      GEN_SERVICE_URL: http://generatedquestservice:8003

  webapp:
    container_name: webapp-${teamname:-defaultASW}
    image: ghcr.io/arquisoft/wiq_es6b/webapp:latest
    profiles: ["dev", "prod"]
    build: ./webapp
    depends_on:
      - gatewayservice
    ports:
      - "3000:3000" 

  prometheus:
    image: prom/prometheus
    container_name: prometheus-${teamname:-defaultASW}
    profiles: ["dev"]
    networks:
      - mynetwork
    volumes:
      - ./gatewayservice/monitoring/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    depends_on: 
      - gatewayservice
      
  grafana:
    image: grafana/grafana
    container_name: grafana-${teamname:-defaultASW}
    profiles: ["dev"]
    networks:
      - mynetwork
    volumes:
      - grafana_data:/var/lib/grafana
      - ./gatewayservice/monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SERVER_HTTP_PORT=9091
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "9091:9091"
    depends_on: 
      - prometheus


volumes:
  mongodb_data:
  prometheus_data: 
  grafana_data: 

networks:
  mynetwork:
    driver: bridge
