openapi: 3.0.0
info:
  title: Generatedquestservice API
  description: GeneratedQuest OpenAPI specification.
  version: 1.0.0
servers:
  - url: http://localhost:8003
    description: Development server
  - url: http://51.142.17.139:8003
    description: Production server
paths:
  /addGeneratedQuestion:
    post:
      summary: Add a generated question.
      operationId: addGeneratedQuestion
      requestBody:
        description: The generated question data to add.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                generatedQuestionBody:
                  type: string
                  description: The body of the generated question.
                correctAnswer:
                  type: string
                  description: The correct answer of the generated question.
      responses:
        '200':
          description: Generated question added successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  generatedQuestionBody:
                    type: string
                    description: The body of the generated question.
                  correctAnswer:
                    type: string
                    description: The correct answer of the generated question.
        '204':
          description: No Content. The question already exists.
        '500':
          description: Internal Server Error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message.
                  details:
                    type: string
                    description: Internal server error.
  /getAllGeneratedQuestions:
    get:
      summary: Retrieve all generated questions.
      operationId: getAllGeneratedQuestions
      responses:
        '200':
          description: Generated questions retrieved successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  description: The generated question object.
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error information.
                    example: Internal Server Error
components:
  schemas:
    GeneratedQuestion:
      type: object
      properties:
        questionBody:
          type: string
          description: The body of the question.
        correcta:
          type: string
          description: The correct answer.
        incorrectas:
          type: array
          items:
            type: string
          description: The incorrect answers.
        numquest:
          type: integer
          description: The number of the question.